version: '3'

volumes:
  supervisor_odoo_data: {}
  supervisor_odoo_db: {}

services:
    broker:
      image: woahbase/alpine-mosquitto
      ports:
        - "1883:1883"
      volumes:
        - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf

    odoo:
      build:
        context: .
        dockerfile: odoo/Dockerfile
      depends_on:
        - db
      ports:
        - "8069:8069"
      volumes:
        - "supervisor_odoo_data:/var/lib/odoo"
        - "./odoo/addons:/mnt/extra-addons"

    db:
      image: postgres:9-alpine
      environment:
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
      volumes:
        - supervisor_odoo_db:/var/lib/db

    http_bridge:
      image: litnimax/mqttrpc_http_bridge
      environment:
        - HTTP_URL=http://odoo:8069/jsonrpc
        - HTTP_LISTEN_ADDRESS=0.0.0.0
        - HTTP_LISTEN_PORT=8888
        - MQTT_URL=mqtt://broker
        - CLIENT_UID=odoo
        - DEBUG=1
        - MQTT_REPLY_TIMEOUT=60
